spring.application.name=zentry-backend
server.port=8080

spring.mongodb.uri=mongodb://localhost:27017/zentry

app.jwt.secret=U29tZVN1cGVyU2VjcmV0S2V5Rm9ySldUVG9rZW5aZW50cnkxMjM0NTY3ODkwMTIzNDU2
app.jwt.expiration=86400000