spring.application.name=zentry-backend
server.port=8080

spring.mongodb.uri=mongodb://localhost:27017/zentry

app.jwt.secret=U29tZVN1cGVyU2VjcmV0S2V5Rm9ySldUVG9rZW5aZW50cnkxMjM0NTY3ODkwMTIzNDU2
app.jwt.expiration=86400000

mailjet.api.key=3ae091908dce08331921f39016964991
mailjet.api.secret=45278a772ed5e27fa98e5e9f3b9d8fe2
mailjet.from.email=paula.burdalo1@educa.madrid.org
mailjet.from.name=Zentry